"""Gale puck identity + DNS generators for the wisp netboot infrastructure.

Two outputs from the same 'Google WiFi Pucks' sheet data
(``inventory.gwifi_pucks``):

- ``generate_gwifi_pucks`` — ``pucks.json`` identity file deployed to
  wisp:/etc/gwifi-netboot/pucks.json. Identity only: names, serials, MACs,
  fixed IPs. All runtime state (arming, installs, phone-home) is
  wisp-internal.
- ``generate_gwifi_pucks_dns`` — dnsmasq ``host-record`` fragment for
  ten64's internal instance (generated/ dir): puck names resolve site-wide
  from ten64 (which is authoritative for the parent zone — nested
  zone-forwards to wisp cannot work).

Both outputs are deterministic (sorted by puck number, no timestamps) so
deploys are idempotent and diffs are clean.

See gwifi-openwrt docs/wisp-netboot-install-design.md (sections 5.3, D7).
"""

from __future__ import annotations

import json

from gdoc2netcfg.models.host import NetworkInventory


def generate_gwifi_pucks(inventory: NetworkInventory) -> str:
    """Generate the pucks.json identity file for wisp's gwifi-netboot."""
    pucks = sorted(inventory.gwifi_pucks, key=lambda p: p.number)
    doc = {
        "version": 1,
        "generated_by": "gdoc2netcfg",
        "pucks": [
            {
                "name": p.name,
                "number": p.number,
                "serial": p.serial,
                "eth0": p.eth0,
                "eth1": p.eth1,
                "ip": p.ip,
            }
            for p in pucks
        ],
    }
    return json.dumps(doc, indent=2) + "\n"


def generate_gwifi_pucks_dns(inventory: NetworkInventory) -> str:
    """Generate dnsmasq host-record lines for puck names (A + PTR)."""
    domain = f"wifi.{inventory.site.domain}"
    lines = [
        "# Generated by gdoc2netcfg gwifi_pucks_dns — puck names for the",
        "# wifi VLAN. host-record provides A + PTR. DHCP for these devices",
        "# lives on wisp (see gwifi-openwrt",
        "# docs/wisp-netboot-install-design.md D7).",
    ]
    for p in sorted(inventory.gwifi_pucks, key=lambda p: p.number):
        lines.append(f"host-record={p.name}.{domain},{p.ip}")
    return "\n".join(lines) + "\n"
