"""PowerDNS Recursor forward-zones file generator (dns-redesign §7).

Emits the recursor's routing table as a YAML forward_zones_file:

- leaf net zones ({net}.{domain}) and their reverse slices (v4 /24s per
  covered third octet, v6 /64s; global VLANs get a whole-second-octet
  v4 /16 slice and a two-nibble v6 /56-style slice) → that net's leaf
  gateway addresses (the router's interface on the net)
- the site zone, wg + transit zones and their central reverses →
  the central auth instance (127.0.0.1:5300)
- delegated nets (fpgas) and their reverses → the delegated server
  (tweed), mirroring today's server=/.../ lines
- peer-site zones → the peer_zones knob (Phase 2 starts at today's wg
  endpoint; Phase 6 flips both sites to the peer central anchors)

The recursor validates DNSSEC on top of this routing; the zones behind
leaf gateways resolve as provably-insecure delegations of the (signed)
site zone (verifications V1/V2).
"""

from __future__ import annotations

from gdoc2netcfg.generators.dnsmasq_leaf import DELEGATED_NETS, _non_leaf_nets
from gdoc2netcfg.generators.pdns_zones import (
    DELEGATED_NET_SERVERS,
    ROUTER_HOSTNAME,
    _central_nets,
)
from gdoc2netcfg.derivations.vlan import ip_to_net
from gdoc2netcfg.models.host import NetworkInventory
from gdoc2netcfg.models.network import Site

CENTRAL_AUTH = "127.0.0.1:5300"

# wg tunnels aren't VLANs; their address space is code-level policy
# (see vlan.ip_to_net): 10.98/16 + legacy 10.255/16, v6 :98xx.
WG_V4_SECOND_OCTETS = (98, 255)
WG_V6_HEXTET_PREFIX = "98"


def generate_recursor_forward(
    inventory: NetworkInventory,
    central_auth: str = CENTRAL_AUTH,
    peer_zones: dict[str, list[str]] | None = None,
) -> str:
    """Generate the recursor forward-zones YAML file content."""
    site = inventory.site
    domain = site.domain

    entries: list[tuple[str, list[str]]] = []

    # Site + central-served child zones → central auth
    entries.append((domain, [central_auth]))
    for net in sorted(_central_nets(site)):
        entries.append((f"{net}.{domain}", [central_auth]))

    # Central reverses: wg v4 /16s + v6 /56-style slice
    for b in WG_V4_SECOND_OCTETS:
        entries.append((f"{b}.10.in-addr.arpa", [central_auth]))
    entries.append(
        (_v6_slice_zone(site, WG_V6_HEXTET_PREFIX), [central_auth])
    )
    # transit VLANs: v4 /24 + v6 /64 → central
    for vlan in site.vlans.values():
        if vlan.is_transit and vlan.transit_match:
            b, c = vlan.transit_match
            entries.append((f"{c}.{b}.10.in-addr.arpa", [central_auth]))
            entries.append(
                (_v6_slice_zone(site, f"{b}{c:02d}"), [central_auth])
            )

    # Delegated nets (fpgas → tweed): forward + reverse, as today
    for net, server in sorted(DELEGATED_NET_SERVERS.items()):
        entries.append((f"{net}.{domain}", [server]))
        vlan = site.vlan_by_name(net)
        if vlan is not None and vlan.is_global:
            entries.append((f"{vlan.id}.10.in-addr.arpa", [server]))

    # Leaf nets → their gateways
    gateways = _leaf_gateways(inventory)
    for net in sorted(gateways):
        forwarders = gateways[net]
        entries.append((f"{net}.{domain}", forwarders))
        entries.extend(
            (zone, forwarders) for zone in _leaf_reverse_zones(site, net)
        )

    # Peer sites (cross-site routing; target flips at Phase 6)
    for zone, forwarders in sorted((peer_zones or {}).items()):
        entries.append((zone, forwarders))

    lines = [
        "# Generated by gdoc2netcfg (recursor_forward) — do not edit.",
        "# Routing: leaf nets -> their dnsmasq leaf gateways; site/transit/wg",
        f"# -> the central auth ({central_auth}); fpgas -> tweed; peers per knob.",
    ]
    for zone, forwarders in entries:
        fwd = ", ".join(f"'{f}'" for f in forwarders)
        lines.append(f"- zone: {zone}")
        lines.append(f"  forwarders: [{fwd}]")
    return "\n".join(lines) + "\n"


def _leaf_gateways(inventory: NetworkInventory) -> dict[str, list[str]]:
    """Leaf net → the router's gateway addresses on that net (v4 then v6)."""
    site = inventory.site
    non_leaf = _non_leaf_nets(site)
    router = inventory.host_by_hostname(ROUTER_HOSTNAME)
    gateways: dict[str, list[str]] = {}
    if router is None:
        return gateways
    for iface in router.interfaces:
        net = ip_to_net(iface.ipv4, site)
        if net is None or net in non_leaf:
            continue
        fwd = gateways.setdefault(net, [])
        fwd.append(str(iface.ipv4))
        fwd.extend(str(a) for a in iface.ipv6_addresses)
    return gateways


def _leaf_reverse_zones(site: Site, net: str) -> list[str]:
    """The reverse zones a leaf net owns: v4 /24 per covered third octet
    and v6 /64 per third octet for site-octet nets; a v4 /16 plus a
    two-nibble v6 slice for global VLANs."""
    vlan = site.vlan_by_name(net)
    zones: list[str] = []
    if vlan is None:
        return zones

    if vlan.is_global:
        zones.append(f"{vlan.id}.10.in-addr.arpa")
        zones.append(_v6_slice_zone(site, f"{vlan.id}"))
        return zones

    for c in vlan.covered_third_octets:
        zones.append(f"{c}.{site.site_octet}.10.in-addr.arpa")
        # full /64: the hextet parses as hex, so '108' is 0x0108 —
        # left-pad to the 4-nibble form
        zones.append(
            _v6_slice_zone(site, f"{site.site_octet}{c:02d}".zfill(4))
        )
    return zones


def _v6_slice_zone(site: Site, hextet_digits: str) -> str:
    """The ip6.arpa zone for a vanity-mapped hextet prefix.

    The site's v6 addressing writes 10.AA.BB.CCC as {prefix}:AABB::CCC
    with the decimal digits used literally as hex nibbles. A full 4-digit
    hextet gives a /64 zone; fewer digits give the covering /60//56/...
    slice (used for global VLANs and wg, whose BB varies).
    """
    prefix = site.active_ipv6_prefixes[0].prefix  # e.g. '2404:e80:a137:'
    prefix_nibbles = "".join(
        part.zfill(4) for part in prefix.rstrip(":").split(":")
    )
    nibbles = prefix_nibbles + hextet_digits
    return ".".join(reversed(nibbles)) + ".ip6.arpa"
