"""rsyslog remote-capture generator (per-net remote syslog design).

One imudp input per served router leg, all on UDP 514 — the log class is
the net the message arrives on. Messages are written to
/var/log/<netname>/<hostname>.log via a per-net dynafile ruleset.

Served nets = the router's leaf-net legs (recursor_forward._leaf_gateways,
i.e. the same derivation as the DNS leaf gateways) minus the untrusted
tmp/guest nets. v4 only — every current sender targets v4.

Safety properties (carried over from the hand-written files this
replaces): remote messages only reach the per-device files (ruleset
isolation + stop), never /var/log/syslog; local messages never reach the
remote dirs; secpath-replace prevents hostile hostnames escaping the
directory; dynafile dirs are auto-created (0755, files root:adm 0640).

Kernel netconsole capture rides the same file: one leg-bound imudp input
per served net on UDP 6666 (the fleet's netconsole port), ruleset
remote-<net>-kernel, files /var/log/<net>/<sender>.kernel.log. Netconsole
payloads are raw printk — no syslog header, no hostname — so filenames
key on the SHORT name extracted from the sender's reverse-DNS name (see
_SHORT_NAME_RE; unresolvable senders degrade to their bare IP) and the
shared KernelLine template stamps wall-clock arrival next to the raw
payload (whose level,seq,monotonic-ts prefix survives for gap
detection). Receive-only for now: the pucks still stream to wisp:6666;
re-pointing them (and retiring wisp's receiver) is a documented
follow-up.
"""

from __future__ import annotations

from gdoc2netcfg.generators.recursor_forward import _leaf_gateways
from gdoc2netcfg.models.host import NetworkInventory

# Untrusted nets never get a syslog input.
EXCLUDED_NETS = frozenset({"tmp", "guest"})

_HEADER = """\
# Generated by gdoc2netcfg (rsyslog) — do not edit.
# Per-net remote syslog capture: one imudp input per router leg, all on
# UDP 514; the class is the net the message arrives on. Replaces the
# hand-written tasmota.conf + z-network-switches.conf (this file now
# performs the single allowed imudp module load).
module(load="imudp")

# Kernel netconsole capture: raw printk datagrams (no syslog header, no
# hostname) arrive on UDP 6666, one leg-bound input per served net.
# Filenames key on the sender's reverse-DNS name; each line is stamped
# with wall-clock arrival time (the payload carries only the extended
# netconsole level,seq,monotonic-ts prefix, preserved for gap detection).
template(name="KernelLine" type="string"
         string="%timegenerated:::date-rfc3339% %rawmsg:::drop-last-lf%\\n")
"""


def _served_legs(inventory: NetworkInventory) -> dict[str, str]:
    """net -> the router's v4 leg address, tmp/guest excluded."""
    legs: dict[str, str] = {}
    for net, forwarders in _leaf_gateways(inventory).items():
        if net in EXCLUDED_NETS:
            continue
        v4 = [a for a in forwarders if ":" not in a]
        if not v4:
            raise ValueError(
                f"rsyslog generator: net {net!r} leg has no IPv4 address — "
                "expected every leaf leg to carry a v4 address"
            )
        legs[net] = v4[0]
    return legs


def _net_block(net: str, addr: str) -> str:
    """Template + ruleset + leg-bound :514 input for one served net."""
    return f"""\
template(name="RemoteLog-{net}" type="string"
         string="/var/log/{net}/%hostname:::secpath-replace%.log")
ruleset(name="remote-{net}") {{
    action(type="omfile" dynaFile="RemoteLog-{net}"
           fileOwner="root" fileGroup="adm"
           fileCreateMode="0640" dirCreateMode="0755")
    stop
}}
input(type="imudp" port="514" address="{addr}" ruleset="remote-{net}")
"""


# Short-name extraction for netconsole senders.
#
# Netconsole payloads carry no hostname, so the name comes from the sender's
# PTR — and in this estate PTRs are ipv4-prefixed, e.g.
# ipv4.wisp.wifi.welland.mithis.com (or ipv4.br-net.ten64.net.<domain> for a
# router leg). Taking the first real label gives wisp/br-net/puck07, so a
# kernel file sits next to its syslog sibling: wisp.kernel.log by wisp.log.
#
# Literal dots are written [.] so the emitted conf needs no backslashes
# (rsyslog's parser treats backslashes in "..." as escapes).
#
# The submatch can only be [a-zA-Z][a-zA-Z0-9-]* — inherently path-safe. The
# FALLBACK is the risky one (a broken or hostile PTR lands there verbatim),
# hence secpath-replace stays on the dynafile. Verified live on rsyslog
# 8.2606: secpath-replace turns ../../etc/passwd into .._.._etc_passwd and
# nothing escapes the directory.
_SHORT_NAME_RE = "^(ipv4[.]|ipv6[.])?([a-zA-Z][a-zA-Z0-9-]*)[.]"


def _kernel_block(net: str, addr: str) -> str:
    """Netconsole template + ruleset + leg-bound :6666 input for one net."""
    return f"""\
template(name="KernelLog-{net}" type="string"
         string="/var/log/{net}/%$.short:::secpath-replace%.kernel.log")
ruleset(name="remote-{net}-kernel") {{
    set $.short = re_extract($fromhost, "{_SHORT_NAME_RE}", 0, 2, "");
    if $.short == "" then {{
        set $.short = $fromhost;
    }}
    action(type="omfile" dynaFile="KernelLog-{net}" template="KernelLine"
           fileOwner="root" fileGroup="adm"
           fileCreateMode="0640" dirCreateMode="0755")
    stop
}}
input(type="imudp" port="6666" address="{addr}" ruleset="remote-{net}-kernel")
"""


_LOGROTATE_HEADER = """\
# Generated by gdoc2netcfg (rsyslog) — do not edit.
# Retention: keep at least one year of daily logs. `notifempty` skips days
# a device sent nothing, so 400 daily archives span >=400 days for a
# chatty device and longer for an intermittent one, comfortably clearing
# the 1-year floor. No maxage: nothing is removed by age, only once the
# count is exceeded.
"""


def _logrotate(nets: list[str]) -> str:
    """One 1-year-floor logrotate stanza per served net's log dir."""
    stanzas = [_LOGROTATE_HEADER]
    for net in nets:
        stanzas.append(f"""\
/var/log/{net}/*.log {{
    daily
    rotate 400
    compress
    delaycompress
    missingok
    notifempty
    postrotate
        /usr/lib/rsyslog/rsyslog-rotate
    endscript
}}
""")
    return "\n".join(stanzas)


def generate_rsyslog(inventory: NetworkInventory) -> dict[str, str]:
    """Generate the rsyslog drop-in + logrotate file.

    Returns deploy-relative paths under etc/ ([generators.rsyslog]
    output_dir = "etc"): rsyslog.d/remote-logs.conf and
    logrotate.d/remote-logs.
    """
    legs = _served_legs(inventory)
    if not legs:
        raise ValueError(
            "rsyslog generator: router has no served legs — check the "
            "inventory has a 'ten64' host with leaf-net interfaces"
        )
    parts = [_HEADER]
    for net in sorted(legs):
        parts.append(_net_block(net, legs[net]))
        parts.append(_kernel_block(net, legs[net]))
    return {
        "rsyslog.d/remote-logs.conf": "\n".join(parts),
        "logrotate.d/remote-logs": _logrotate(sorted(legs)),
    }
