"""rsyslog remote-capture generator (per-net remote syslog design).

One imudp input per served router leg, all on UDP 514 — the log class is
the net the message arrives on. Messages are written to
/var/log/<netname>/<hostname>.log via a per-net dynafile ruleset.

Served nets = the router's leaf-net legs (recursor_forward._leaf_gateways,
i.e. the same derivation as the DNS leaf gateways) minus the untrusted
tmp/guest nets. v4 only — every current sender targets v4.

Safety properties (carried over from the hand-written files this
replaces): remote messages only reach the per-device files (ruleset
isolation + stop), never /var/log/syslog; local messages never reach the
remote dirs; secpath-replace prevents hostile hostnames escaping the
directory; dynafile dirs are auto-created (0755, files root:adm 0640).

A transition input on 10514 feeds remote-net so existing switch/wisp
senders keep logging until they are re-pointed at <net-leg>:514
(dropping it is a documented follow-up, spec §out-of-scope).
"""

from __future__ import annotations

from gdoc2netcfg.generators.recursor_forward import _leaf_gateways
from gdoc2netcfg.models.host import NetworkInventory

# Untrusted nets never get a syslog input.
EXCLUDED_NETS = frozenset({"tmp", "guest"})

_HEADER = """\
# Generated by gdoc2netcfg (rsyslog) — do not edit.
# Per-net remote syslog capture: one imudp input per router leg, all on
# UDP 514; the class is the net the message arrives on. Replaces the
# hand-written tasmota.conf + z-network-switches.conf (this file now
# performs the single allowed imudp module load).
module(load="imudp")
"""

_TRANSITION = """\
# Transition input: switches + wisp still send to :10514 — keep feeding
# them into /var/log/net/ until they are re-pointed at the net leg :514.
input(type="imudp" port="10514" ruleset="remote-net")
"""


def _served_legs(inventory: NetworkInventory) -> dict[str, str]:
    """net -> the router's v4 leg address, tmp/guest excluded."""
    legs: dict[str, str] = {}
    for net, forwarders in _leaf_gateways(inventory).items():
        if net in EXCLUDED_NETS:
            continue
        v4 = [a for a in forwarders if ":" not in a]
        if v4:
            legs[net] = v4[0]
    return legs


def _net_block(net: str, addr: str) -> str:
    return f"""\
template(name="RemoteLog-{net}" type="string"
         string="/var/log/{net}/%hostname:::secpath-replace%.log")
ruleset(name="remote-{net}") {{
    action(type="omfile" dynaFile="RemoteLog-{net}"
           fileOwner="root" fileGroup="adm"
           fileCreateMode="0640" dirCreateMode="0755")
    stop
}}
input(type="imudp" port="514" address="{addr}" ruleset="remote-{net}")
"""


def _logrotate(nets: list[str]) -> str:
    """Logrotate stanzas for the per-net log dirs — Task 2 fills this in."""
    return ""


def generate_rsyslog(inventory: NetworkInventory) -> dict[str, str]:
    """Generate the rsyslog drop-in + logrotate file.

    Returns deploy-relative paths under etc/ ([generators.rsyslog]
    output_dir = "etc"): rsyslog.d/remote-logs.conf and
    logrotate.d/remote-logs.
    """
    legs = _served_legs(inventory)
    if not legs:
        raise ValueError(
            "rsyslog generator: router has no served legs — check the "
            "inventory has a 'ten64' host with leaf-net interfaces"
        )
    if "net" not in legs:
        raise ValueError(
            "rsyslog generator: router has no 'net' leg — the 10514 "
            "transition input needs the remote-net ruleset"
        )

    parts = [_HEADER]
    parts.extend(_net_block(net, legs[net]) for net in sorted(legs))
    parts.append(_TRANSITION)
    return {
        "rsyslog.d/remote-logs.conf": "\n".join(parts),
        "logrotate.d/remote-logs": _logrotate(sorted(legs)),
    }
